const defaultState =
[
  { type: "R", side: "W" },
  { type: "N", side: "W" },
  { type: "B", side: "W" },
  { type: "Q", side: "W" },
  { type: "K", side: "W" },
  { type: "B", side: "W" },
  { type: "N", side: "W" },
  { type: "R", side: "W" },
  { type: "P", side: "W" },
  { type: "P", side: "W" },
  { type: "P", side: "W" },
  { type: "P", side: "W" },
  { type: "P", side: "W" },
  { type: "P", side: "W" },
  { type: "P", side: "W" },
  { type: "P", side: "W" },
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  { type: "P", side: "W" },
  { type: "P", side: "W" },
  { type: "P", side: "W" },
  { type: "P", side: "W" },
  { type: "P", side: "W" },
  { type: "P", side: "W" },
  { type: "P", side: "W" },
  { type: "P", side: "W" },
  { type: "R", side: "B" },
  { type: "N", side: "B" },
  { type: "B", side: "B" },
  { type: "Q", side: "B" },
  { type: "K", side: "B" },
  { type: "B", side: "B" },
  { type: "N", side: "B" },
  { type: "R", side: "B" },
];

const match = (state = defaultState, action) => {
  switch (action.type) {
    default:
      return state;
  }
}

export default match;
